# Assignment_7 #
# NAME: Mohammad Issa
# ID:1210047

* Import Libraries:

In [16]:
import pandas as pd

* Load  CSV data:
* Description: "House Prices - Advanced Regression Techniques" dataset. This dataset contains various features about houses, including ordinal and nominal features, and a numeric target feature (SalePrice).

In [17]:
# Getting the csv file of the dataset & its path using read function 
data_path = 'C:\\Users\\HP\\Downloads\\train.csv' 
df = pd.read_csv(data_path)
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

* describing the dataBase by using describe method to give some piece of information

In [18]:

# Display the information about the dataset
print("Dataset Information:")
print(df.info())

# Display the summary statistics for numerical columns
print("\nSummary Statistics for Numerical Columns:")
print(df.describe())

# Display the first few rows of the dataset
print("\nFirst Few Rows of the Dataset:")
print(df.head())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB
None

Summary Statistics for Numerical Columns:
                Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000
mean    730.500000    56.897260    70.049958   10516.828082     6.099315
std     421.610009    42.300571    24.284752    9981.264932     1.382997
min       1.000000    20.000000    21.000000    1300.000000     1.000000
25%     365.750000    20.000000    59.000000    7553.500000     5.000000
50%     730.500000    50.000000    69.000000    9478.500000     6.000000
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000
max    1460.000000   190.000000   313.000000  215245.000000    10.000000

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000  ...
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726  ...
std       1.112799    30.202904     20.645407   181.066207   456.098091  ...
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000  ...
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000  ...
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000  ...
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  1460.000000  1460.000000    1460.000000  1460.000000  1460.000000
mean     94.244521    46.660274      21.954110     3.409589    15.060959
std     125.338794    66.256028      61.119149    29.317331    55.757415
min       0.000000     0.000000       0.000000     0.000000     0.000000
25%       0.000000     0.000000       0.000000     0.000000     0.000000
50%       0.000000    25.000000       0.000000     0.000000     0.000000
75%     168.000000    68.000000       0.000000     0.000000     0.000000
max     857.000000   547.000000     552.000000   508.000000   480.000000

          PoolArea       MiscVal       MoSold       YrSold      SalePrice
count  1460.000000   1460.000000  1460.000000  1460.000000    1460.000000
mean      2.758904     43.489041     6.321918  2007.815753  180921.195890
std      40.177307    496.123024     2.703626     1.328095   79442.502883
min       0.000000      0.000000     1.000000  2006.000000   34900.000000
25%       0.000000      0.000000     5.000000  2007.000000  129975.000000
50%       0.000000      0.000000     6.000000  2008.000000  163000.000000
75%       0.000000      0.000000     8.000000  2009.000000  214000.000000
max     738.000000  15500.000000    12.000000  2010.000000  755000.000000

[8 rows x 38 columns]

First Few Rows of the Dataset:
   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg
1   2          20       RL         80.0     9600   Pave   NaN      Reg
2   3          60       RL         68.0    11250   Pave   NaN      IR1
3   4          70       RL         60.0     9550   Pave   NaN      IR1
4   5          60       RL         84.0    14260   Pave   NaN      IR1

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12

  YrSold  SaleType  SaleCondition  SalePrice
0   2008        WD         Normal     208500
1   2007        WD         Normal     181500
2   2008        WD         Normal     223500
3   2006        WD        Abnorml     140000
4   2008        WD         Normal     250000

[5 rows x 81 columns]

### Dictionary

#### Features

1. **OverallQual**: Ordinal
   - **Description**: Rates the overall material and finish of the house.
   - **Values**: 1 (Very Poor) to 10 (Very Excellent)

2. **YearBuilt**: Numerical
   - **Description**: Original construction date of the house.
   - **Values**: Year (e.g., 2003)

3. **TotalBsmtSF**: Numerical
   - **Description**: Total square feet of the basement area.
   - **Values**: Continuous (e.g., 856)

4. **GrLivArea**: Numerical
   - **Description**: Above grade (ground) living area square feet.
   - **Values**: Continuous (e.g., 1710)

5. **GarageCars**: Ordinal
   - **Description**: Size of the garage in car capacity.
   - **Values**: 0 to 4

6. **MSZoning**: Nominal
   - **Description**: Identifies the general zoning classification of the sale.
   - **Values**: 
     - RL: Residential Low Density
     - RM: Residential Medium Density
     - C (all): Commercial
     - FV: Floating Village Residential
     - RH: Residential High Density

7. **Neighborhood**: Nominal
   - **Description**: Physical locations within Ames city limits.
   - **Values**: Various neighborhood names (e.g., CollgCr, Veenker, Crawfor)

8. **HouseStyle**: Nominal
   - **Description**: The style of dwelling.
   - **Values**: 
     - 1Story: One story
     - 1.5Fin: One and one-half story: 2nd level finished
     - 1.5Unf: One and one-half story: 2nd level unfinished
     - 2Story: Two story
     - 2.5Fin: Two and one-half story: 2nd level finished
     - 2.5Unf: Two and one-half story: 2nd level unfinished
     - SFoyer: Split Foyer
     - SLvl: Split Level

#### Target

1. **SalePrice**: Numerical
   - **Description**: The property's sale price in dollars.
   - **Values**: Continuous (e.g., 208500)

## Defining the modules that will be used

In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

### Data Preprocessing Steps

1. **Removing Irrelevant or Constant Features**
   - Dropped the `Id` column as it does not contribute to the model.

In [20]:

# 1. Removing irrelevant or constant features
irrelevant_features = ['Id', 'Utilities', 'Street', 'PoolQC', 'Condition2', 'RoofMatl', 'MiscFeature']
df = df.drop(columns=irrelevant_features)

# Verify if there are any constant columns left
constant_columns = [col for col in df.columns if df[col].nunique() == 1]
df = df.drop(columns=constant_columns)
df

,MSSubClass,MSZoning,LotFrontage,LotArea,Alley,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,...,3SsnPorch,ScreenPorch,PoolArea,Fence,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,NaN,Reg,Lvl,Inside,Gtl,CollgCr,...,0,0,0,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,NaN,Reg,Lvl,FR2,Gtl,Veenker,...,0,0,0,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,NaN,IR1,Lvl,Inside,Gtl,CollgCr,...,0,0,0,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,NaN,IR1,Lvl,Corner,Gtl,Crawfor,...,0,0,0,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,NaN,IR1,Lvl,FR2,Gtl,NoRidge,...,0,0,0,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,NaN,Reg,Lvl,Inside,Gtl,Gilbert,...,0,0,0,NaN,0,8,2007,WD,Normal,175000
1456,20,RL,85.0,13175,NaN,Reg,Lvl,Inside,Gtl,NWAmes,...,0,0,0,MnPrv,0,2,2010,WD,Normal,210000
1457,70,RL,66.0,9042,NaN,Reg,Lvl,Inside,Gtl,Crawfor,...,0,0,0,GdPrv,2500,5,2010,WD,Normal,266500
1458,20,RL,68.0,9717,NaN,Reg,Lvl,Inside,Gtl,NAmes,...,0,0,0,NaN,0,4,2010,WD,Normal,142125
1459,20,RL,75.0,9937,NaN,Reg,Lvl,Inside,Gtl,Edwards,...,0,0,0,NaN,0,6,2008,WD,Normal,147500


2. **Verifying Data Types**
   - Ensured that numerical features are correctly identified as numeric and ordinal features are recognized appropriately.

In [21]:
# 2. Verifying data types
print(df.dtypes)

MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Alley             object
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 74, dtype: object

3. **Removing Duplicates**
   - Checked and removed any duplicate rows in the dataset.

In [22]:
# 3. Removing duplicates
df = df.drop_duplicates()
df.duplicated().sum()

0

4. **Defining Feature Matrix and Target Vector**
   - Selected `OverallQual`, `YearBuilt`, `TotalBsmtSF`, `GrLivArea`, and `GarageCars` as features.
   - Defined `SalePrice` as the target variable.

In [23]:
# 4. Defining feature matrix and target vector
features = ['OverallQual', 'YearBuilt', 'TotalBsmtSF', 'GrLivArea', 'GarageCars', 'MSZoning', 'Neighborhood', 'HouseStyle']
target = 'SalePrice'
X = df[features]
y = df[target]
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OverallQual   1460 non-null   int64
 1   YearBuilt     1460 non-null   int64
 2   TotalBsmtSF   1460 non-null   int64
 3   GrLivArea     1460 non-null   int64
 4   GarageCars    1460 non-null   int64
 5   MSZoning      1460 non-null   object
 6   Neighborhood  1460 non-null   object
 7   HouseStyle    1460 non-null   object
dtypes: int64(5), object(3)
memory usage: 91.4+ KB

5. **Splitting the Data to Train and Test Sets**
   - Split the data into 80% training and 20% testing sets using a specified `random_state` (The ID)for reproducibility.

In [24]:
# 5. Splitting the data to train and test sets
student_id = 1210047  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=student_id)
X_train

,OverallQual,YearBuilt,TotalBsmtSF,GrLivArea,GarageCars,MSZoning,Neighborhood,HouseStyle
368,5,1954,1268,1268,1,RL,NAmes,1Story
1088,7,2004,970,1709,2,RM,Edwards,2Story
1185,5,1924,784,1221,1,RL,Edwards,1.5Fin
446,6,1966,1517,1888,2,RL,NAmes,1Story
1412,4,1949,0,1040,2,RL,NAmes,1Story
...,...,...,...,...,...,...,...,...
571,6,1959,864,864,1,RL,NAmes,1Story
341,4,1950,721,841,1,RH,SawyerW,1Story
840,6,1925,672,1482,1,RH,SWISU,2Story
189,8,2001,1593,1593,2,RL,StoneBr,1Story
1422,6,2003,848,848,2,RM,CollgCr,1Story

6. **Handling Missing Values**
   - Applied median imputation for missing values in numerical features.
   - Used the most frequent value imputation for missing values in ordinal features.

In [25]:
# Define list of categorical features
cat_cols = X_train.select_dtypes(include=['object', 'category']).columns

# Define list of numerical features
num_cols = X_train.select_dtypes(include=['number']).columns

# Instantiate the imputer with the desired strategy
impute_na = SimpleImputer(strategy='constant', fill_value='NA')
impute_median = SimpleImputer(strategy='median')

# Fit the imputer object on the categorical training data
X_train[cat_cols] = impute_na.fit_transform(X_train[cat_cols])
X_test[cat_cols] = impute_na.transform(X_test[cat_cols])

# Fit the imputer object on the numerical training data
X_train[num_cols] = impute_median.fit_transform(X_train[num_cols])
X_test[num_cols] = impute_median.transform(X_test[num_cols])

7. **Encoding Categorical Data**
   - Encoded ordinal features using ordinal encoding.

In [26]:
# Define the numerical, ordinal, and nominal features
numeric_features = ['YearBuilt', 'TotalBsmtSF', 'GrLivArea']
ordinal_features = ['OverallQual', 'GarageCars']
nominal_features = ['MSZoning', 'Neighborhood', 'HouseStyle']

# Separate features
X_numeric_train = X_train[numeric_features]
X_ordinal_train = X_train[ordinal_features]
X_nominal_train = X_train[nominal_features]

# Encode ordinal features
encoder_ord = OrdinalEncoder()
X_ordinal_train_encoded = encoder_ord.fit_transform(X_ordinal_train)

# Encode nominal features using one-hot encoding
encoder_nom = OneHotEncoder(handle_unknown='ignore', sparse_output=False) 
X_nominal_train_encoded = encoder_nom.fit_transform(X_nominal_train)

8. **Feature Scaling**
   - Scaled numerical features to standardize the range of values.

In [27]:
import numpy as np
# Scale numerical features
scaler = StandardScaler()
X_numeric_train_scaled = scaler.fit_transform(X_numeric_train)

# Concatenate all preprocessed features
X_train_processed = np.concatenate([X_numeric_train_scaled, X_ordinal_train_encoded, X_nominal_train_encoded], axis=1)

# Repeat preprocessing for the test set
X_numeric_test = X_test[numeric_features]
X_ordinal_test = X_test[ordinal_features]
X_nominal_test = X_test[nominal_features]

X_numeric_test_scaled = scaler.transform(X_numeric_test)
X_ordinal_test_encoded = encoder_ord.transform(X_ordinal_test)
X_nominal_test_encoded = encoder_nom.transform(X_nominal_test)

X_test_processed = np.concatenate([X_numeric_test_scaled, X_ordinal_test_encoded, X_nominal_test_encoded], axis=1)

1. Fit a Linear Regression Model on the Transformed Data

In [28]:
from sklearn.linear_model import LinearRegression

# Initialize the linear regression model
model = LinearRegression()

# Fit the model on the transformed training data
model.fit(X_train_processed, y_train)

LinearRegression()

2. Print the Model Parameters and Provide an Interpretation

In [29]:
# Print the coefficients and intercept
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

# Mapping feature names to coefficients for interpretation
feature_names = (numeric_features + 
                 ordinal_features + 
                 encoder_nom.get_feature_names_out(nominal_features).tolist())

coefficients = model.coef_

# Print the feature names and their corresponding coefficients
for feature, coef in zip(feature_names, coefficients):
    print(f"{feature}: {coef}")

Intercept: -7810204134910826.0
Coefficients: [ 5.21285893e+03  3.76922371e+03  3.09482437e+04  1.65034081e+04
  1.25793141e+04  3.80615830e+16  3.80615830e+16  3.80615830e+16
  3.80615830e+16  3.80615830e+16 -1.70086042e+15 -1.70086042e+15
 -1.70086042e+15 -1.70086042e+15 -1.70086042e+15 -1.70086042e+15
 -1.70086042e+15 -1.70086042e+15 -1.70086042e+15 -1.70086042e+15
 -1.70086042e+15 -1.70086042e+15 -1.70086042e+15 -1.70086042e+15
 -1.70086042e+15 -1.70086042e+15 -1.70086042e+15 -1.70086042e+15
 -1.70086042e+15 -1.70086042e+15 -1.70086042e+15 -1.70086042e+15
 -1.70086042e+15 -1.70086042e+15 -1.70086042e+15 -2.85505185e+16
 -2.85505185e+16 -2.85505185e+16 -2.85505185e+16 -2.85505185e+16
 -2.85505185e+16 -2.85505185e+16 -2.85505185e+16]
YearBuilt: 5212.858929598184
TotalBsmtSF: 3769.2237145436957
GrLivArea: 30948.24374492987
OverallQual: 16503.40812428785
GarageCars: 12579.314136768618
MSZoning_C (all): 3.806158304627834e+16
MSZoning_FV: 3.806158304630674e+16
MSZoning_RH: 3.806158304630261e+16
MSZoning_RL: 3.8061583046314376e+16
MSZoning_RM: 3.806158304630034e+16
Neighborhood_Blmngtn: -1700860415763728.8
Neighborhood_Blueste: -1700860415751084.0
Neighborhood_BrDale: -1700860415755315.8
Neighborhood_BrkSide: -1700860415732715.8
Neighborhood_ClearCr: -1700860415723987.5
Neighborhood_CollgCr: -1700860415742663.8
Neighborhood_Crawfor: -1700860415723210.8
Neighborhood_Edwards: -1700860415761387.8
Neighborhood_Gilbert: -1700860415748118.8
Neighborhood_IDOTRR: -1700860415737051.0
Neighborhood_MeadowV: -1700860415742126.2
Neighborhood_Mitchel: -1700860415754245.8
Neighborhood_NAmes: -1700860415752969.8
Neighborhood_NPkVill: -1700860415764558.2
Neighborhood_NWAmes: -1700860415758621.0
Neighborhood_NoRidge: -1700860415680651.5
Neighborhood_NridgHt: -1700860415699160.5
Neighborhood_OldTown: -1700860415750883.2
Neighborhood_SWISU: -1700860415751421.0
Neighborhood_Sawyer: -1700860415751634.8
Neighborhood_SawyerW: -1700860415750942.2
Neighborhood_Somerst: -1700860415731817.0
Neighborhood_StoneBr: -1700860415691506.2
Neighborhood_Timber: -1700860415730627.0
Neighborhood_Veenker: -1700860415717569.0
HouseStyle_1.5Fin: -2.8550518495594132e+16
HouseStyle_1.5Unf: -2.8550518495591892e+16
HouseStyle_1Story: -2.855051849557865e+16
HouseStyle_2.5Fin: -2.855051849559198e+16
HouseStyle_2.5Unf: -2.855051849560667e+16
HouseStyle_2Story: -2.8550518495596796e+16
HouseStyle_SFoyer: -2.85505184955738e+16
HouseStyle_SLvl: -2.8550518495581916e+16

* Explanation:
### Interpretation:

* Intercept: The intercept is the expected mean value of the target (SalePrice) when all predictors are set to zero.
* Coefficients: Each coefficient represents the change in the target (SalePrice) for a one-unit change in the respective feature, holding all other features constant.

3. Evaluate the Model's Quality Using Appropriate Metrics

In [30]:
from sklearn.metrics import mean_squared_error, r2_score

# Predict on the training set
y_train_pred = model.predict(X_train_processed)

# Predict on the test set
y_test_pred = model.predict(X_test_processed)

# Calculate and print the metrics
train_mse = mean_squared_error(y_train, y_train_pred)
train_r2 = r2_score(y_train, y_train_pred)

test_mse = mean_squared_error(y_test, y_test_pred)
test_r2 = r2_score(y_test, y_test_pred)

print(f"Training MSE: {train_mse}")
print(f"Training R2: {train_r2}")

print(f"Test MSE: {test_mse}")
print(f"Test R2: {test_r2}")

Training MSE: 1168416179.4666095
Training R2: 0.8039943144393813
Test MSE: 1215131243.3938355
Test R2: 0.8403504394270993

4. Determine if the Model Exhibits Overfitting or Underfitting
Overfitting vs. Underfitting:

* Overfitting: The model performs well on the training data but poorly on the test data. This is indicated by a significantly lower MSE and higher R² score on the training set compared to the test set.
* Underfitting: The model performs poorly on both the training and test data, indicated by high MSE and low R² scores on both sets.
### Analysis:

* Compare the MSE and R² scores on the training and test sets.
* If the test MSE is much higher than the training MSE and the test R² is much lower than the training R², the model may be overfitting.
* If both MSEs are high and both R² scores are low, the model may be underfitting.

5. Provide Link to Your Selected Dataset in Kaggle
The dataset used in this example is "House Prices: Advanced Regression Techniques" from Kaggle. Here is the link to the dataset:
* Link-->https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/data

* Thannk You 
* Mohammad Issa